In [15]:
# import libraries

import numpy as np

Creating a numpy matrix

In [16]:
m1 = np.array([[2, 4], [5, 8]])

print(m1)

print()

print(f"The shape is: {m1.shape}")

[[2 4]
 [5 8]]

The shape is: (2, 2)


In [17]:
m2 = np.array([[1, 2, 4], [3, 5, 8], [6, 7, 9]])

print(m2)

print()

print(f"The shape is: {m2.shape}")

[[1 2 4]
 [3 5 8]
 [6 7 9]]

The shape is: (3, 3)


Creating matrix with random value

In [18]:
m3 = np.random.rand(3,3)

print(m3)

print()

print(f"The shape is: {m3.shape}")

[[0.12954074 0.98382671 0.66172648]
 [0.79609594 0.21743339 0.24473027]
 [0.7699315  0.1130381  0.68129894]]

The shape is: (3, 3)


In [19]:
m4 = np.random.randint(100, size=(4,5))

print(m4)

print()

print(f"The shape is: {m4.shape}")

[[92 34  2 36 49]
 [66 47 60 73 27]
 [89 54  6 46 69]
 [30 22 14 33 34]]

The shape is: (4, 5)


Matrix with all zeros (Null Matrix), ones

In [20]:
m5 = np.zeros((4,4))

print(m5)

print()

print(f"The shape is: {m5.shape}")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

The shape is: (4, 4)


In [21]:
m6 = np.ones((4,4))

print(m6)

print()

print(f"The shape is: {m6.shape}")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

The shape is: (4, 4)


In [22]:
m7 = np.ones((4,4), dtype=int)

print(m7)

print()

print(f"The shape is: {m7.shape}")

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

The shape is: (4, 4)


Identity matrix

In [23]:
m8 = np.eye(3)

print(m8)

print()

print(f"The shape is: {m8.shape}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

The shape is: (3, 3)


In [24]:
m9 = np.eye(3, dtype=int)

print(m9)

print()

print(f"The shape is: {m9.shape}")

[[1 0 0]
 [0 1 0]
 [0 0 1]]

The shape is: (3, 3)


Transpose matrix

In [25]:
m10 = np.random.randint(100, size=(4,5))

print(m10)

print()

print(f"The shape is: {m10.shape}")

[[53 98 87 71 74]
 [86 78 88 63 63]
 [24 21  3 65 50]
 [29 92 75 17 53]]

The shape is: (4, 5)


In [28]:
m10_transpose = np.transpose(m10)

print(m10_transpose)

print()

print(f"The shape is: {m10_transpose.shape}")

[[53 86 24 29]
 [98 78 21 92]
 [87 88  3 75]
 [71 63 65 17]
 [74 63 50 53]]

The shape is: (5, 4)
