In [1]:
# importing libraries

import numpy as np

**Matrix Addition: Both matrices should be of same shape**

In [6]:
m1 = np.array([[2,4],[5,8]])
m2 = np.array([[3,6],[4,7]])

print(m1)
print()
print(m2)
print()

m3 = m1 + m2
m4 = np.add(m1,m2)

print(m3)
print()
print(m4)

[[2 4]
 [5 8]]

[[3 6]
 [4 7]]

[[ 5 10]
 [ 9 15]]

[[ 5 10]
 [ 9 15]]


**Matrix Subtraction: Both matrices should be of same shape**

In [7]:
m1 = np.array([[2,4],[5,8]])
m2 = np.array([[3,6],[4,7]])

print(m1)
print()
print(m2)
print()

m3 = m1 - m2
m4 = np.subtract(m1,m2)

print(m3)
print()
print(m4)

[[2 4]
 [5 8]]

[[3 6]
 [4 7]]

[[-1 -2]
 [ 1  1]]

[[-1 -2]
 [ 1  1]]


**Multiplying matrix by a scalar**

In [8]:
x = 5

m1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(m1)
print()
product = x * m1

print(product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


**Multiplying 2 matrices**

In [21]:
m1 = np.random.randint(1,10,(4,5))
m2 = np.random.randint(1,10,(5,4))

print(m1)
print()
print(m2)
print()

product = np.dot(m1,m2)

print(product)
print()
print(product.shape)

[[3 7 6 7 6]
 [5 4 5 2 6]
 [8 1 9 6 9]
 [1 6 9 8 1]]

[[5 5 9 9]
 [5 4 5 1]
 [9 8 3 9]
 [2 5 4 6]
 [7 2 7 2]]

[[160 138 150 142]
 [136 103 130 118]
 [201 164 191 208]
 [139 143 105 146]]

(4, 4)


**Multiplying 2 matrices (Element wise)**

In [23]:
m1 = np.random.randint(1,10,(4,4))
m2 = np.random.randint(1,10,(4,4))

print(m1)
print()
print(m2)
print()

product = np.multiply(m1,m2)

print(product)
print()
print(product.shape)

[[7 9 1 3]
 [9 6 2 5]
 [8 4 2 9]
 [3 1 4 9]]

[[8 9 7 3]
 [1 8 8 4]
 [8 8 5 5]
 [5 1 5 8]]

[[56 81  7  9]
 [ 9 48 16 20]
 [64 32 10 45]
 [15  1 20 72]]

(4, 4)
