In [2]:
import numpy as np

# Arrays using lists

## 1d array

In [3]:
x = np.array([1,2,3,4,5])
print(f"x = {x}")

print(f"x has dimensions: {x.shape}")
print(f"x is an object of type: {type(x)}")
print(f"The elements in x are of type: {x.dtype}")

x = [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


## 2d arrays

In [4]:
# 2d array
y = np.array([[1,2,3,4],[5,6,7,8]])
print(f"y = {y}")

print(f"y has dimensions: {y.shape}")
print(f"y is an object of type: {type(y)}")
print(f"The elements in y are of type: {y.dtype}")

y = [[1 2 3 4]
 [5 6 7 8]]
y has dimensions: (2, 4)
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


### Changing Data Type

In [5]:
# change datatype

a = np.array([1.2, 2.7, 3.5, 4.8, 5.5], dtype=np.int64)
print(a)

[1 2 3 4 5]


### Saving & Loading Arrays

In [6]:
# save the array for later use
b = np.array([1,2,3,4])
np.save('my_array', b)

In [7]:
# load the saved array
c = np.load('my_array.npy')
print(c)

[1 2 3 4]


# Arrays using built in functions

In [8]:
d = np.zeros((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
e = np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
f = np.full((2,3), 3)
print(f)

[[3 3 3]
 [3 3 3]]


## Identity array

In [11]:
g = np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Diagonal Array

In [12]:
h = np.diag([10,20,30,40,50])
print(h)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


## Random nd arrays

In [13]:
i = np.random.random((3,3))
print(i)

[[0.72854797 0.69685071 0.4406814 ]
 [0.89744268 0.8977565  0.34047553]
 [0.92053152 0.69921281 0.41351016]]


In [14]:
j = np.random.randint(1,5,size=(3,3))
print(j)

[[4 3 4]
 [4 2 2]
 [1 2 2]]


## Evenly spaced arrays

In [15]:
k = np.arange(10)
print(k)
l = np.arange(4,10)
print(l)
m = np.arange(1,14,3)
print(m)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [16]:
n = np.linspace(1,10,3)
print(n)

[ 1.   5.5 10. ]


In [17]:
o = np.arange(20).reshape(4,5)
print(o)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Array Analysis

In [18]:
p = np.random.randint(10,90,(5,5))
print(p)

[[65 71 76 68 52]
 [17 59 28 51 21]
 [86 21 40 61 30]
 [73 25 19 31 43]
 [24 34 13 79 61]]


In [19]:
print(p.shape)

(5, 5)


In [20]:
print(p.ndim)

2


In [21]:
print(p.size)

25


In [22]:
print(p.dtype)

int32


# Arithematic Operations

In [23]:
q = np.array([1,2,3,4,5])
r = np.array([1.5,2.5,3.5,4.5,5.5])

In [24]:
print(q + r)
print('\n')
print(np.add(q,r))

[ 2.5  4.5  6.5  8.5 10.5]


[ 2.5  4.5  6.5  8.5 10.5]


In [25]:
print(q - r)
print('\n')
print(np.subtract(q,r))

[-0.5 -0.5 -0.5 -0.5 -0.5]


[-0.5 -0.5 -0.5 -0.5 -0.5]


In [26]:
print(q * r)
print('\n')
print(np.multiply(q,r))

[ 1.5  5.  10.5 18.  27.5]


[ 1.5  5.  10.5 18.  27.5]


In [27]:
print(q / r)
print('\n')
print(np.divide(q,r))

[0.66666667 0.8        0.85714286 0.88888889 0.90909091]


[0.66666667 0.8        0.85714286 0.88888889 0.90909091]


In [28]:
print(np.exp(q))
print(np.sqrt(q))
print(np.power(q,2))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


# Transpose Array

In [29]:
s = np.random.randint(1,10,(2,5))
print(s)
print(s.shape)
trans = np.transpose(s)
print(trans)
print(trans.shape)

[[7 4 3 6 2]
 [5 4 7 2 2]]
(2, 5)
[[7 5]
 [4 4]
 [3 7]
 [6 2]
 [2 2]]
(5, 2)


# Boolean Indexing

In [30]:
t = np.arange(25).reshape(5,5)
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
print(t[t>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [32]:
print(t[t<=7])

[0 1 2 3 4 5 6 7]


In [33]:
print(t[(t > 10) & (t < 17)])

[11 12 13 14 15 16]


In [34]:
t[(t > 10) & (t < 17)] = -1
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


# Set Operations

In [35]:
u = np.array([1,2,3,4,5])
v = np.array([6,7,2,8,4])

In [36]:
print(f"Elements present in both u and v: {np.intersect1d(u,v)}")
print(f"Elements present in u that are not in v: {np.setdiff1d(u,v)}")
print(f"All elements of u and v: {np.union1d(u,v)}")

Elements present in both u and v: [2 4]
Elements present in u that are not in v: [1 3 5]
All elements of u and v: [1 2 3 4 5 6 7 8]


# Sorting

## 1d array

In [37]:
w = np.random.randint(1, 11, size = (10))
print(f"Before sorting: {w}")

Before sorting: [ 9  1  5  7  5  6  1 10  4  8]


In [38]:
print(f"After Sorting (out of place): {np.sort(w)}") # Used as a function
print(f"After sorting: {w}") # Original array remain intact

After Sorting (out of place): [ 1  1  4  5  5  6  7  8  9 10]
After sorting: [ 9  1  5  7  5  6  1 10  4  8]


In [39]:
w.sort() # Used as a method
print(f"After Sorting (In place): {w}")

After Sorting (In place): [ 1  1  4  5  5  6  7  8  9 10]


In [40]:
print(f"After Sorting (Unique values): {np.sort(np.unique(w))}")

After Sorting (Unique values): [ 1  4  5  6  7  8  9 10]


## 2d array

In [41]:
x = np.random.randint(1, 11, size = (5,5))
print(f"Original array x:\n{x}")

Original array x:
[[ 9  4  9  1 10]
 [ 2  6  7 10  1]
 [ 9  4  7  2  9]
 [ 3  2  2  3  9]
 [ 4  2  4  7  5]]


In [42]:
print(f"x with sorted columns:\n{np.sort(x, axis=0)}")

x with sorted columns:
[[ 2  2  2  1  1]
 [ 3  2  4  2  5]
 [ 4  4  7  3  9]
 [ 9  4  7  7  9]
 [ 9  6  9 10 10]]


In [43]:
print(f"x with sorted rows:\n{np.sort(x, axis=1)}")

x with sorted rows:
[[ 1  4  9  9 10]
 [ 1  2  6  7 10]
 [ 2  4  7  9  9]
 [ 2  2  3  3  9]
 [ 2  4  4  5  7]]


### Accessing, Inserting & Deleting elements into nd Arrays

In [44]:
y = np.array([1,2,3,4,5])

print(f"The original array is: {y}")
print(f"The second element in the array is: {y[1]}")

y[3] = 20 # Update element using index position
print(f"The updated array is: {y}")

The original array is: [1 2 3 4 5]
The second element in the array is: 2
The updated array is: [ 1  2  3 20  5]


In [45]:
z = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f"The original array is:\n{z}")
print(f"The element at (1,1) in the array is: {z[1,1]}")

z[0,0] = 20 # Update element using index position
print(f"The updated array is:\n{z}")

The original array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The element at (1,1) in the array is: 5
The updated array is:
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [46]:
# Deleting elements
y = np.delete(y, [0,4])
print(f"The updated array is: {y}")

z = np.delete(z, 0, axis = 0)
print(f"The updated array is:\n{z}")

z = np.delete(z, [0,2], axis = 1)
print(f"The updated array is:\n{z}")

The updated array is: [ 2  3 20]
The updated array is:
[[4 5 6]
 [7 8 9]]
The updated array is:
[[5]
 [8]]


In [47]:
# Appending values
y = np.array([1,2,3,4,5])
z = np.array([[1,2,3], [4,5,6], [7,8,9]])

y = np.append(y, 6)
print(f"The updated array is: {y}")


z = np.append(z, [[10,11,12]], axis = 0)
print(f"The updated array is:\n{z}")

The updated array is: [1 2 3 4 5 6]
The updated array is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
# Inserting values
y = np.array([1,2,3,4,5])
z = np.array([[1,2,3], [4,5,6], [7,8,9]])

y = np.insert(y, 1, [10, 11])
print(f"The updated array is: {y}")

z = np.insert(z, 0, [[10,11,12]], axis = 0)
print(f"The updated array is:\n{z}")

z = np.insert(z, 0, [[100,111,122, 134]], axis = 1)
print(f"The updated array is:\n{z}")


The updated array is: [ 1 10 11  2  3  4  5]
The updated array is:
[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
The updated array is:
[[100  10  11  12]
 [111   1   2   3]
 [122   4   5   6]
 [134   7   8   9]]


In [49]:
# Stacking arrays

x = np.array([1,2])
y = np.array([[3,4], [5,6]])

z = np.hstack((y, x.reshape(2,1)))
print(f"The updated array is:\n{z}")

w = np.vstack((x,y))
print(f"The updated array is:\n{w}")

The updated array is:
[[3 4 1]
 [5 6 2]]
The updated array is:
[[1 2]
 [3 4]
 [5 6]]


# Slicing nd arrays

In [50]:
x = np.arange(20).reshape(4,5)
print(f"Original array:\n{x}")

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [51]:
# Select all elements from 2nd till 4th row and in 3rd to 5th column

z = x[1:4, 2:5]
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [52]:
# Select elements from 2nd to last row and 3rd to 5th column
w = x[1:, 2:5]
print(w)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [53]:
# Select elements from 1st to 3rd row and 3rd to 5th column
y = x[:3, 2:5]
print(y)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [54]:
# Select all elements in 3rd row
v = x[2, :]
print(v)

[10 11 12 13 14]


In [55]:
# Extract diagonals

print(np.diag(x))
print(np.diag(x, k = 1))
print(np.diag(x, k = -1))


[ 0  6 12 18]
[ 1  7 13 19]
[ 5 11 17]


# Statistical functions

In [56]:
x = np.array([[1,2], [3,4]])

print(x.mean())
print(x.mean(axis = 0))
print(x.mean(axis = 1))
print(x.sum())
print(x.sum(axis = 0))
print(x.sum(axis = 1))
print(x.std())
print(x.std(axis = 0))
print(x.std(axis = 1))
print(np.median(x))
print(np.median(x, axis = 0))
print(np.median(x, axis = 1))
print(x.min())
print(x.min(axis = 0))
print(x.min(axis = 1))
print(x.max())
print(x.max(axis = 0))
print(x.max(axis = 1))

2.5
[2. 3.]
[1.5 3.5]
10
[4 6]
[3 7]
1.118033988749895
[1. 1.]
[0.5 0.5]
2.5
[2. 3.]
[1.5 3.5]
1
[1 2]
[1 3]
4
[3 4]
[2 4]
